cmsproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views
from .api import api_router

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),
    url(r'^api/v2/', api_router.urls),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wagtailmedia/models.py
from __future__ import unicode_literals

import os.path

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import Signal
from django.dispatch.dispatcher import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from taggit.managers import TaggableManager

try:
    from django.urls import reverse
except ImportError:  # fallback for older versions of Django
    from django.core.urlresolvers import reverse

try:
    from wagtail.admin.utils import get_object_usage
    from wagtail.core.models import CollectionMember
    from wagtail.search import index
    from wagtail.search.queryset import SearchableQuerySetMixin
except ImportError:  # fallback for wagtail <2.0
    from wagtail.wagtailadmin.utils import get_object_usage
    from wagtail.wagtailcore.models import CollectionMember
    from wagtail.wagtailsearch import index
    from wagtail.wagtailsearch.queryset import SearchableQuerySetMixin


class MediaQuerySet(SearchableQuerySetMixin, models.QuerySet):
    pass


@python_2_unicode_compatible
class AbstractMedia(CollectionMember, index.Indexed, models.Model):
    MEDIA_TYPES = (
        ('audio', _('Audio file')),
        ('video', _('Video file')),
    )

    title = models.CharField(max_length=255, verbose_name=_('title'))
    file = models.FileField(upload_to='media', verbose_name=_('file'))

    type = models.CharField(choices=MEDIA_TYPES, max_length=255, blank=False, null=False)
    duration = models.PositiveIntegerField(verbose_name=_('duration'), help_text=_('Duration in seconds'))
    width = models.PositiveIntegerField(null=True, blank=True, verbose_name=_('width'))
    height = models.PositiveIntegerField(null=True, blank=True, verbose_name=_('height'))
    thumbnail = models.FileField(upload_to='media_thumbnails', blank=True, verbose_name=_('thumbnail'))

    created_at = models.DateTimeField(verbose_name=_('created at'), auto_now_add=True)
    uploaded_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('uploaded by user'),
        null=True,
        blank=True,
        editable=False,
        on_delete=models.SET_NULL
    )

    tags = TaggableManager(help_text=None, blank=True, verbose_name=_('tags'))

    objects = MediaQuerySet.as_manager()

    search_fields = CollectionMember.search_fields + [
        index.SearchField('title', partial_match=True, boost=10),
        index.RelatedFields('tags', [
            index.SearchField('name', partial_match=True, boost=10),
        ]),
        index.FilterField('uploaded_by_user'),
    ]

    def __str__(self):
        return self.title

    @property
    def filename(self):
        return os.path.basename(self.file.name)

    @property
    def thumbnail_filename(self):
        return os.path.basename(self.thumbnail.name)

    @property
    def file_extension(self):
        return os.path.splitext(self.filename)[1][1:]

    @property
    def url(self):
        return self.file.url

    def get_usage(self):
        return get_object_usage(self)

    @property
    def usage_url(self):
        return reverse('wagtailmedia:media_usage',
                       args=(self.id,))

    def is_editable_by_user(self, user):
        from wagtailmedia.permissions import permission_policy
        return permission_policy.user_has_permission_for_instance(user, 'change', self)

    class Meta:
        abstract = True
        verbose_name = _('media')


class Media(AbstractMedia):
    admin_form_fields = (
        'title',
        'file',
        'collection',
        'duration',
        'width',
        'height',
        'thumbnail',
        'tags',
    )


def get_media_model():
    from django.conf import settings
    from django.apps import apps

    try:
        app_label, model_name = settings.WAGTAILMEDIA_MEDIA_MODEL.split('.')
    except AttributeError:
        return Media
    except ValueError:
        raise ImproperlyConfigured("WAGTAILMEDIA_MEDIA_MODEL must be of the form 'app_label.model_name'")

    media_model = apps.get_model(app_label, model_name)
    if media_model is None:
        raise ImproperlyConfigured(
            "WAGTAILMEDIA_MEDIA_MODEL refers to model '%s' that has not been installed" %
            settings.WAGTAILMEDIA_MEDIA_MODEL
        )
    return media_model


# Receive the pre_delete signal and delete the file associated with the model instance.
@receiver(pre_delete, sender=Media)
def media_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.file.delete(False)
    instance.thumbnail.delete(False)


media_served = Signal(providing_args=['request'])

wagtailmedia/views/chooser.py
import json

from django.shortcuts import get_object_or_404, render

from wagtailmedia.models import get_media_model
from wagtailmedia.permissions import permission_policy

try:
    from django.urls import reverse
except ImportError:  # fallback for older Django
    from django.core.urlresolvers import reverse

try:
    from wagtail.utils.pagination import paginate
    from wagtail.admin.forms import SearchForm
    from wagtail.admin.modal_workflow import render_modal_workflow
    from wagtail.admin.utils import PermissionPolicyChecker
    from wagtail.core.models import Collection
except ImportError:  # fallback for wagtail <2.0
    from wagtail.utils.pagination import paginate
    from wagtail.wagtailadmin.forms import SearchForm
    from wagtail.wagtailadmin.modal_workflow import render_modal_workflow
    from wagtail.wagtailadmin.utils import PermissionPolicyChecker
    from wagtail.wagtailcore.models import Collection


permission_checker = PermissionPolicyChecker(permission_policy)


def get_media_json(media):
    """
    helper function: given a media, return the json to pass back to the
    chooser panel
    """

    return json.dumps({
        'id': media.id,
        'title': media.title,
        'edit_link': reverse('wagtailmedia:edit', args=(media.id,)),
    })


def chooser(request):
    Media = get_media_model()

    media_files = []

    q = None
    is_searching = False
    if 'q' in request.GET or 'p' in request.GET or 'collection_id' in request.GET:
        media_files = Media.objects.all()

        collection_id = request.GET.get('collection_id')
        if collection_id:
            media_files = media_files.filter(collection=collection_id)

        searchform = SearchForm(request.GET)
        if searchform.is_valid():
            q = searchform.cleaned_data['q']

            media_files = media_files.search(q)
            is_searching = True
        else:
            media_files = media_files.order_by('-created_at')
            is_searching = False

        # Pagination
        paginator, media_files = paginate(request, media_files, per_page=10)

        return render(request, "wagtailmedia/chooser/results.html", {
            'media_files': media_files,
            'query_string': q,
            'is_searching': is_searching,
        })
    else:
        searchform = SearchForm()

        collections = Collection.objects.all()
        if len(collections) < 2:
            collections = None

        media_files = Media.objects.order_by('-created_at')
        paginator, media_files = paginate(request, media_files, per_page=10)

    return render_modal_workflow(request, 'wagtailmedia/chooser/chooser.html', 'wagtailmedia/chooser/chooser.js', {
        'media_files': media_files,
        'searchform': searchform,
        'collections': collections,
        'is_searching': False,
    })


def media_chosen(request, media_id):
    media = get_object_or_404(get_media_model(), id=media_id)

    return render_modal_workflow(
        request, None, 'wagtailmedia/chooser/media_chosen.js',
        {'media_json': get_media_json(media)}
    )

wagtailmedia/views/media.py
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext as _
from django.views.decorators.vary import vary_on_headers

from wagtailmedia.forms import get_media_form
from wagtailmedia.models import get_media_model
from wagtailmedia.permissions import permission_policy

try:
    from django.urls import reverse
except ImportError:  # fallback for older Django
    from django.core.urlresolvers import reverse

try:
    from wagtail.utils.pagination import paginate
    from wagtail.admin import messages
    from wagtail.admin.forms import SearchForm
    from wagtail.admin.utils import (
        PermissionPolicyChecker, permission_denied, popular_tags_for_model
    )
    from wagtail.core.models import Collection
    from wagtail.search.backends import get_search_backends
except ImportError:  # fallback for wagtail <2.0
    from wagtail.utils.pagination import paginate
    from wagtail.wagtailadmin import messages
    from wagtail.wagtailadmin.forms import SearchForm
    from wagtail.wagtailadmin.utils import (
        PermissionPolicyChecker, permission_denied, popular_tags_for_model
    )
    from wagtail.wagtailcore.models import Collection
    from wagtail.wagtailsearch.backends import get_search_backends


permission_checker = PermissionPolicyChecker(permission_policy)


@permission_checker.require_any('add', 'change', 'delete')
@vary_on_headers('X-Requested-With')
def index(request):
    Media = get_media_model()

    # Get media files (filtered by user permission)
    media = permission_policy.instances_user_has_any_permission_for(
        request.user, ['change', 'delete']
    )

    # Ordering
    if 'ordering' in request.GET and request.GET['ordering'] in ['title', '-created_at']:
        ordering = request.GET['ordering']
    else:
        ordering = '-created_at'
    media = media.order_by(ordering)

    # Filter by collection
    current_collection = None
    collection_id = request.GET.get('collection_id')
    if collection_id:
        try:
            current_collection = Collection.objects.get(id=collection_id)
            media = media.filter(collection=current_collection)
        except (ValueError, Collection.DoesNotExist):
            pass

    # Search
    query_string = None
    if 'q' in request.GET:
        form = SearchForm(request.GET, placeholder=_("Search media files"))
        if form.is_valid():
            query_string = form.cleaned_data['q']
            media = media.search(query_string)
    else:
        form = SearchForm(placeholder=_("Search media"))

    # Pagination
    paginator, media = paginate(request, media)

    collections = permission_policy.collections_user_has_any_permission_for(
        request.user, ['add', 'change']
    )
    if len(collections) < 2:
        collections = None

    # Create response
    if request.is_ajax():
        return render(request, 'wagtailmedia/media/results.html', {
            'ordering': ordering,
            'media_files': media,
            'query_string': query_string,
            'is_searching': bool(query_string),
        })
    else:
        return render(request, 'wagtailmedia/media/index.html', {
            'ordering': ordering,
            'media_files': media,
            'query_string': query_string,
            'is_searching': bool(query_string),

            'search_form': form,
            'popular_tags': popular_tags_for_model(Media),
            'user_can_add': permission_policy.user_has_permission(request.user, 'add'),
            'collections': collections,
            'current_collection': current_collection,
        })


@permission_checker.require('add')
def add(request, media_type):
    Media = get_media_model()
    MediaForm = get_media_form(Media)

    if request.POST:
        media = Media(uploaded_by_user=request.user, type=media_type)
        form = MediaForm(request.POST, request.FILES, instance=media, user=request.user)
        if form.is_valid():
            form.save()

            # Reindex the media entry to make sure all tags are indexed
            for backend in get_search_backends():
                backend.add(media)

            messages.success(request, _("Media file '{0}' added.").format(media.title), buttons=[
                messages.button(reverse('wagtailmedia:edit', args=(media.id,)), _('Edit'))
            ])
            return redirect('wagtailmedia:index')
        else:
            messages.error(request, _("The media file could not be saved due to errors."))
    else:
        media = Media(uploaded_by_user=request.user, type=media_type)
        form = MediaForm(user=request.user, instance=media)

    return render(request, "wagtailmedia/media/add.html", {
        'form': form,
        'media_type': media_type,
    })


@permission_checker.require('change')
def edit(request, media_id):
    Media = get_media_model()
    MediaForm = get_media_form(Media)

    media = get_object_or_404(Media, id=media_id)

    if not permission_policy.user_has_permission_for_instance(request.user, 'change', media):
        return permission_denied(request)

    if request.POST:
        original_file = media.file
        form = MediaForm(request.POST, request.FILES, instance=media, user=request.user)
        if form.is_valid():
            if 'file' in form.changed_data:
                # if providing a new media file, delete the old one.
                # NB Doing this via original_file.delete() clears the file field,
                # which definitely isn't what we want...
                original_file.storage.delete(original_file.name)
            media = form.save()

            # Reindex the media entry to make sure all tags are indexed
            for backend in get_search_backends():
                backend.add(media)

            messages.success(request, _("Media file '{0}' updated").format(media.title), buttons=[
                messages.button(reverse('wagtailmedia:edit', args=(media.id,)), _('Edit'))
            ])
            return redirect('wagtailmedia:index')
        else:
            messages.error(request, _("The media could not be saved due to errors."))
    else:
        form = MediaForm(instance=media, user=request.user)

    filesize = None

    # Get file size when there is a file associated with the Media object
    if media.file:
        try:
            filesize = media.file.size
        except OSError:
            # File doesn't exist
            pass

    if not filesize:
        messages.error(
            request,
            _("The file could not be found. Please change the source or delete the media file"),
            buttons=[messages.button(reverse('wagtailmedia:delete', args=(media.id,)), _('Delete'))]
        )

    return render(request, "wagtailmedia/media/edit.html", {
        'media': media,
        'filesize': filesize,
        'form': form,
        'user_can_delete': permission_policy.user_has_permission_for_instance(
            request.user, 'delete', media
        ),
    })


@permission_checker.require('delete')
def delete(request, media_id):
    Media = get_media_model()
    media = get_object_or_404(Media, id=media_id)

    if not permission_policy.user_has_permission_for_instance(request.user, 'delete', media):
        return permission_denied(request)

    if request.POST:
        media.delete()
        messages.success(request, _("Media file '{0}' deleted.").format(media.title))
        return redirect('wagtailmedia:index')

    return render(request, "wagtailmedia/media/confirm_delete.html", {
        'media': media,
    })


def usage(request, media_id):
    Media = get_media_model()
    media = get_object_or_404(Media, id=media_id)

    paginator, used_by = paginate(request, media.get_usage())

    return render(request, "wagtailmedia/media/usage.html", {
        'media': media,
        'used_by': used_by
    })

wagtailmedia/templates/wagtailmedia/media/_file_field.html
{% extends "wagtailadmin/shared/field.html" %}
{% load i18n %}
{% block form_field %}
    <a href="{{ media.url }}" class="icon icon-media">{{ media.filename }}</a><br /><br />
    {% trans "Change media file:" %}
    {{ field }}
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/_file_field_as_li.html
{% load wagtailadmin_tags %}
<li class="{% if field.field.required %}required{% endif %} {{ wrapper_classes }} {{ li_classes }} {% if field.errors %}error{% endif %}">
    {% include "wagtailmedia/media/_file_field.html" %}
</li>

wagtailmedia/templates/wagtailmedia/media/_thumbnail_field.html
{% extends "wagtailadmin/shared/field.html" %}
{% load i18n %}
{% block form_field %}

    {% if media.thumbnail %}
        <a href="{{ media.thumbnail.url }}" class="icon icon-image">{{ media.thumbnail_filename }}</a><br /><br />
    {% endif %}

    {% trans "Change thumbnail file:" %}
    {{ field }}
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/_thumbnail_field_as_li.html
{% load wagtailadmin_tags %}
<li class="{% if field.field.required %}required{% endif %} {{ wrapper_classes }} {{ li_classes }} {% if field.errors %}error{% endif %}">
    {% include "wagtailmedia/media/_thumbnail_field.html" %}
</li>

wagtailmedia/templates/wagtailmedia/media/add.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% load wagtailimages_tags %}
{% block titletag %}
    {% if media_type == 'audio' %}
        {% trans "Add audio" %}
    {% else %}
        {% trans "Add video" %}
    {% endif %}
{% endblock %}

{% block extra_js %}
    {{ block.super }}

    {% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
    <script>
        $(function() {
            $('#id_tags').tagit({
                autocomplete: {source: "{{ autocomplete_url|addslashes }}"}
            });
        });
    </script>
{% endblock %}

{% block content %}
    {% if media_type == 'audio' %}
        {% trans "Add audio" as add_str %}
    {% else %}
        {% trans "Add video" as add_str %}
    {% endif %}
    {% include "wagtailadmin/shared/header.html" with title=add_str icon="media" %}

    <div class="nice-padding">
        <form action="{% url 'wagtailmedia:add' media_type %}" method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <ul class="fields">
                {% for field in form %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=field %}
                {% endfor %}
                <li>
                    <button type="submit" class="button button-longrunning" data-clicked-text="{% trans 'Uploading...' %}"><span class="icon icon-spinner"></span><em>{% trans 'Upload' %}</em></button>
                </li>
            </ul>
        </form>
    </div>
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load wagtailadmin_tags i18n %}
{% block titletag %}{% blocktrans with title=media.title %}Delete {{ title }}{% endblocktrans %}{% endblock %}
{% block content %}
    {% trans "Delete media file" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str subtitle=media.title icon="media" %}

    <div class="nice-padding">
        {% usage_count_enabled as uc_enabled %}
        {% if uc_enabled %}
            <div class="usagecount">
                <a href="{{ media.usage_url }}">{% blocktrans count usage_count=media.get_usage.count %}Used {{ usage_count }} time{% plural %}Used {{ usage_count }} times{% endblocktrans %}</a>
            </div>
        {% endif %}

        <p>{% trans "Are you sure you want to delete this media file?" %}</p>
        <form action="{% url 'wagtailmedia:delete' media.id %}" method="POST" novalidate>
            {% csrf_token %}
            <input type="submit" value='{% trans "Yes, delete" %}' class="button serious" />
        </form>
    </div>
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/edit.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% load wagtailimages_tags wagtailadmin_tags %}
{% block titletag %}{% blocktrans with title=media.title %}Editing {{ title }}{% endblocktrans %}{% endblock %}

{% block extra_js %}
    {{ block.super }}

    {% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
    <script>
        $(function() {
            $('#id_tags').tagit({
                autocomplete: {source: "{{ autocomplete_url|addslashes }}"}
            });
        });
    </script>
{% endblock %}

{% block content %}
    {% trans "Editing" as editing_str %}
    {% include "wagtailadmin/shared/header.html" with title=editing_str subtitle=media.title icon="media" usage_object=media %}

    <div class="row row-flush nice-padding">

        <div class="col10 divider-after">
            <form action="{% url 'wagtailmedia:edit' media.id %}" method="POST" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <ul class="fields">
                    {% for field in form %}
                        {% if field.name == 'file' %}
                            {% include "wagtailmedia/media/_file_field_as_li.html" %}
                        {% elif field.name == 'thumbnail' %}
                            {% include "wagtailmedia/media/_thumbnail_field_as_li.html" %}
                        {% else %}
                            {% include "wagtailadmin/shared/field_as_li.html" %}
                        {% endif %}
                    {% endfor %}
                    <li>
                        <input class="button" type="submit" value="{% trans 'Save' %}" />
                        {% if user_can_delete %}
                            <a href="{% url 'wagtailmedia:delete' media.id %}" class="button button-secondary no">{% trans "Delete" %}</a>
                        {% endif %}
                    </li>
                </ul>
            </form>
        </div>
        <div class="col2">
            <dl>
                {% if media.file %}
                    <dt>{% trans "Filesize" %}</dt>
                    <dd>{% if filesize %}{{ filesize|filesizeformat }}{% else %}{% trans "File not found" %}{% endif %}</dd>
                {% endif %}

                {% usage_count_enabled as uc_enabled %}
                {% if uc_enabled %}
                    <dt>{% trans "Usage" %}</dt>
                    <dd>
                        <a href="{{ media.usage_url }}">{% blocktrans count usage_count=media.get_usage.count %}Used {{ usage_count }} time{% plural %}Used {{ usage_count }} times{% endblocktrans %}</a>
                    </dd>
                {% endif %}
            </dl>
        </div>
    </div>


    </div>
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}Media{% endblock %}
{% block extra_js %}
    {{ block.super }}
    <script>
        window.headerSearch = {
            url: "{% url 'wagtailmedia:index' %}",
            termInput: "#id_q",
            targetOutput: "#media-results"
        };

        $(function() {
            $('#collection_chooser_collection_id').change(function() {
                this.form.submit();
            })
        });
    </script>
{% endblock %}

{% block content %}
    {% trans "Media" as media_str %}
    <header class="nice-padding">
        <div class="row">
            <div class="left">
                <div class="col">
                    <h1 class="icon icon-media">
                    {{ media_str }}
                    </h1>
                </div>
                <form class="col search-form" action="{% url 'wagtailmedia:index' %}{% if query_parameters %}?{{ query_parameters }}{% endif %}" method="get" novalidate>
                    <ul class="fields">
                        {% for field in search_form %}
                            {% include "wagtailadmin/shared/field_as_li.html" with field=field field_classes="field-small iconfield" input_classes="icon-search" %}
                        {% endfor %}
                        <li class="submit visuallyhidden"><input type="submit" value="Search" class="button" /></li>
                    </ul>
                </form>
            </div>
            {% if user_can_add %}
                <div class="right">
                    <div class="addbutton">
                        <a href="{% url 'wagtailmedia:add' 'audio' %}" class="button bicolor icon icon-plus">{% trans "Add audio" %}</a>
                    </div>
                </div>
                <div class="right">
                    <div class="col">
                        <div class="addbutton">
                            <a href="{% url 'wagtailmedia:add' 'video' %}" class="button bicolor icon icon-plus">{% trans "Add video" %}</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </header>

    <div class="nice-padding">
        {% if collections %}
            <form class="image-search search-bar" action="{% url 'wagtailmedia:index' %}" method="GET" novalidate>
                <ul class="fields">
                    {% include "wagtailadmin/shared/collection_chooser.html" %}
                </ul>
            </form>
        {% endif %}

        <div id="media-results" class="media">
            {% include "wagtailmedia/media/results.html" %}
        </div>
    </div>
{% endblock %}

wagtailmedia/templates/wagtailmedia/media/list.html
{% load i18n %}
<table class="listing">
    <col />
    <col  />
    <col width="16%" />
    <thead>
        <tr class="table-headers">
            <th>
                {% if not is_searching %}
                    <a href="{% url 'wagtailmedia:index' %}{% if not ordering == "title" %}?ordering=title{% endif %}" class="icon icon-arrow-down-after {% if  ordering == "title" %}teal{% endif %}">
                        {% trans "Title" %}
                    </a>
                {% else %}
                    {% trans "Title" %}
                {% endif %}
            </th>
            <th>{% trans "File" %}</th>
            <th>{% trans "Type" %}</th>
            <th>
                {% if not is_searching %}
                    <a href="{% url 'wagtailmedia:index' %}{% if not ordering == "-created_at" %}?ordering=-created_at{% endif %}" class="icon icon-arrow-down-after {% if  ordering == "-created_at" %}teal{% endif %}">
                        {% trans "Uploaded" %}
                    </a>
                {% else %}
                    {% trans "Uploaded" %}
                {% endif %}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for media_file in media_files %}
            <tr>
                <td class="title">
                    {% if choosing %}
                        <h2><a href="{% url 'wagtailmedia:media_chosen' media_file.id %}" class="media-choice">{{ media_file.title }}</a></h2>
                    {% else %}
                        <h2><a href="{% url 'wagtailmedia:edit' media_file.id %}">{{ media_file.title }}</a></h2>
                    {% endif %}
                </td>
                <td>
                    {% if choosing %}
                        {{ media_file.filename }}
                    {% else %}
                        <a href="{{ media_file.url }}" class="nolink">{{ media_file.filename }}</a>
                    {% endif %}
                </td>
                <td>{{ media_file.get_type_display }}</td>
                <td><div class="human-readable-date" title="{{ media_file.created_at|date:"d M Y H:i" }}">{{ media_file.created_at|timesince }} ago</div></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

wagtailmedia/templates/wagtailmedia/media/results.html
{% load i18n wagtailadmin_tags %}
{% if media_files %}
    {% if is_searching %}
        <h2>
        {% blocktrans count counter=media_files|length %}
            There is one match
        {% plural %}
            There are {{ counter }} matches
        {% endblocktrans %}
        </h2>
        
        {% search_other %}
    {% endif %}

    {% include "wagtailmedia/media/list.html" %}

    {% include "wagtailadmin/shared/pagination_nav.html" with items=media_files is_searching=is_searching linkurl="wagtailmedia:index" %}
{% else %}
    {% if is_searching %}
         <h2>{% blocktrans %}Sorry, no media files match "<em>{{ query_string }}</em>"{% endblocktrans %}</h2>
         
         {% search_other %}
    {% else %}
        {% url 'wagtailmedia:add' 'audio' as wagtailmedia_add_audio_url %}
        {% url 'wagtailmedia:add' 'video' as wagtailmedia_add_video_url %}
        {% if current_collection %}
            <p>{% blocktrans %}You haven't uploaded any media files in this collection. You can upload <a href="{{ wagtailmedia_add_audio_url }}">audio</a> or <a href="{{ wagtailmedia_add_video_url }}">video</a> files.{% endblocktrans %}</p>
        {% else %}
            <p>{% blocktrans %}You haven't uploaded any media files. You can upload <a href="{{ wagtailmedia_add_audio_url }}">audio</a> or <a href="{{ wagtailmedia_add_video_url }}">video</a> files.{% endblocktrans %}</p>
        {% endif %}
    {% endif %}
{% endif %}